"""empty message

Revision ID: 130b81d2390f
Revises: f746474c6397
Create Date: 2025-05-09 22:57:47.314761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130b81d2390f'
down_revision: Union[str, None] = 'f746474c6397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecules', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
