"""empty message

Revision ID: 324396b43f42
Revises: 
Create Date: 2024-05-17 13:25:39.325413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324396b43f42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('old_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('old_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('molecules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cas', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cas', 'image_id', 'smiles', name='cas_image_smiles_constraint')
    )
    op.create_table('ligands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('molecule_id', sa.Integer(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('pages', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('title')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('molecule_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('time', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('solvent', sa.String(), nullable=True),
    sa.Column('freshly_prepared', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('commercial_name', sa.String(), nullable=True),
    sa.Column('clinical_name', sa.String(), nullable=True),
    sa.Column('cLogP', sa.String(), nullable=True),
    sa.Column('logP', sa.String(), nullable=True),
    sa.Column('logD', sa.String(), nullable=True),
    sa.Column('solubility', sa.String(), nullable=True),
    sa.Column('log_kw', sa.String(), nullable=True),
    sa.Column('log_k30', sa.String(), nullable=True),
    sa.Column('log_k0', sa.String(), nullable=True),
    sa.Column('cell_line', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecules.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'molecule_id', 'method', 'time', 'solvent', 'cell_line', name='experiments_constraint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiments')
    op.drop_table('papers')
    op.drop_table('ligands')
    op.drop_table('molecules')
    op.drop_table('journals')
    # ### end Alembic commands ###
