"""empty message

Revision ID: 4c80b0c606f9
Revises: 51955e488c0f
Create Date: 2024-08-04 16:41:20.995075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c80b0c606f9'
down_revision: Union[str, None] = '51955e488c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_p', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nh_oh_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_h_acceptors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_h_donors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_rotatable_bonds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exact_mol_wt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('num_of_atoms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecules', schema=None) as batch_op:
        batch_op.drop_column('num_of_atoms')
        batch_op.drop_column('exact_mol_wt')
        batch_op.drop_column('num_rotatable_bonds')
        batch_op.drop_column('num_h_donors')
        batch_op.drop_column('num_h_acceptors')
        batch_op.drop_column('no_count')
        batch_op.drop_column('nh_oh_count')
        batch_op.drop_column('mr')
        batch_op.drop_column('log_p')

    # ### end Alembic commands ###
