"""empty message

Revision ID: 51955e488c0f
Revises: 324396b43f42
Create Date: 2024-06-03 00:29:24.531793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51955e488c0f'
down_revision: Union[str, None] = '324396b43f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smiles_with_props', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligands', schema=None) as batch_op:
        batch_op.drop_column('smiles_with_props')

    # ### end Alembic commands ###
