"""empty message

Revision ID: a05209c43f84
Revises: d5f300372d14
Create Date: 2025-07-19 16:48:50.566562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05209c43f84'
down_revision: Union[str, None] = 'd5f300372d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
