"""empty message

Revision ID: b53e42e2b7a8
Revises: 4c80b0c606f9
Create Date: 2024-08-04 18:26:08.772221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53e42e2b7a8'
down_revision: Union[str, None] = '4c80b0c606f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clog_p', sa.Float(), nullable=True))
        batch_op.drop_column('log_p')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_p', sa.FLOAT(), nullable=True))
        batch_op.drop_column('clog_p')

    # ### end Alembic commands ###
