"""empty message

Revision ID: f746474c6397
Revises: b53e42e2b7a8
Create Date: 2024-12-03 01:21:56.771224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f746474c6397'
down_revision: Union[str, None] = 'b53e42e2b7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aLogP', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('logS', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stability', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('in_vivo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stability_proofs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stability_proofs_desc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_column('stability_proofs_desc')
        batch_op.drop_column('stability_proofs')
        batch_op.drop_column('in_vivo')
        batch_op.drop_column('stability')
        batch_op.drop_column('logS')
        batch_op.drop_column('aLogP')

    # ### end Alembic commands ###
